# Generated by Django 4.2.5 on 2023-10-06 14:18

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=60, unique=True, validators=[shop.models.validate_slug_without_underlines], verbose_name='URL-идентификатор'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(max_length=60, unique=True, validators=[shop.models.validate_slug_without_underlines], verbose_name='URL-идентификатор'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color_of_base_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.colorsofbaseproduct', verbose_name='Базовый товар и его цвет'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='slug',
            field=models.SlugField(max_length=70, validators=[shop.models.validate_slug_without_underlines], verbose_name='URL-идентификатор варианта товара'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Объем (л)'),
        ),
    ]
