# Generated by Django 4.2.5 on 2023-10-17 08:16

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_collection_description_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.collection', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='colors',
            field=models.ManyToManyField(related_name='products', through='shop.ColorsOfBaseProduct', to='shop.color', verbose_name='Цвета базового товара'),
        ),
        migrations.AlterField(
            model_name='colorsofbaseproduct',
            name='base_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colorsOfVariants', to='shop.baseproduct', verbose_name='Базовый товар'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color_of_base_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.colorsofbaseproduct', verbose_name='Базовый товар и его цвет'),
        ),
        migrations.AlterField(
            model_name='productvariantimg',
            name='image',
            field=models.ImageField(upload_to=shop.models.productVariantImg_directory_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productvariantimg',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.productvariant', verbose_name='Вариант товара'),
        ),
        migrations.CreateModel(
            name='ColorOfProductImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, default='', max_length=150, verbose_name='alt-текст для SEO')),
                ('image', models.ImageField(upload_to=shop.models.colorOfProductImg_directory_path, verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color_of_base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.colorsofbaseproduct', verbose_name='Цвет базового товара')),
            ],
            options={
                'verbose_name': 'Изображение цвета базового товара',
                'verbose_name_plural': 'Изображения цвета базового товара',
                'get_latest_by': ['created_at'],
            },
        ),
    ]
