# Generated by Django 4.2.5 on 2023-10-24 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_baseproduct_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'get_latest_by': ['created_at'], 'ordering': ['order'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'get_latest_by': ['created_at'], 'ordering': ['order'], 'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.collection', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='baseproductimg',
            name='base_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.baseproduct', verbose_name='Базовый товар'),
        ),
        migrations.AlterField(
            model_name='colorofproductimg',
            name='color_of_base_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='shop.colorsofbaseproduct', verbose_name='Цвет базового товара'),
        ),
        migrations.AlterField(
            model_name='productvariantimg',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='shop.productvariant', verbose_name='Вариант товара'),
        ),
    ]
