# Generated by Django 4.2.5 on 2023-11-10 14:37

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_options_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproductimg',
            name='image',
            field=models.ImageField(max_length=255, upload_to=shop.models.baseProductImg_directory_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(max_length=255, upload_to=shop.models.categoryImg_directory_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(max_length=255, upload_to=shop.models.collectionImg_directory_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='colorofproductimg',
            name='image',
            field=models.ImageField(max_length=255, upload_to=shop.models.colorOfProductImg_directory_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productvariantimg',
            name='image',
            field=models.ImageField(max_length=255, upload_to=shop.models.productVariantImg_directory_path, verbose_name='Изображение'),
        ),
    ]
